# Generated by Django 2.1 on 2018-08-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180829_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.CharField(max_length=10000),
        ),
    ]
