#!/usr/bin/env python3

import argparse
import os
import requests

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

parser = argparse.ArgumentParser(description='Script for testing "review-django" REST API.')
parser.add_argument('url', metavar='URL', nargs=1)
parser.add_argument('auth', metavar='USERNAME:PASSWORD', nargs=1)
parser.add_argument('--file', dest='file', metavar='JSON_FILE', nargs=1)

args = vars(parser.parse_args())

url = args.get('url')[0]
username, password = args.get('auth')[0].split(':')

method = 'GET'
if args.get('file'):
    path = os.path.join(BASE_DIR, 'data', args.get('file')[0])
    with open(path) as data_file:
        data = data_file.read()
        method = 'POST'

headers = {
    'content-type': 'application/json'
}

if method == 'POST':
    response = requests.post(url, data=data, headers=headers, auth=(username, password))
else:
    response = requests.get(url, auth=(username, password))

print(response.status_code)
print(response.text)
